version: '3.8'

services:
  # server:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   container_name: server
  #   environment:
  #    NODE_ENV: development-docker
  #   ports:
  #     - '3000:3000'
  #   networks:
  #     - sportship-network
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #   restart: 'unless-stopped'
  #   depends_on:
  #     - keycloak

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
    container_name: mysql
    ports:
      - 3306:3306
    networks:
      - sportship-network
    restart: 'unless-stopped'
    volumes:
      - kcdata:/var/lib/mysql
      # - /opt/pastech/keycloak/data:/var/lib/mysql

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      - DB_VENDOR=MYSQL
      - DB_ADDR=mysql
      - DB_DATABASE=keycloak
      # this is not ideal
      - DB_USER=root
      - DB_PASSWORD=root
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=adminkc
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/sportship-realm.json
    container_name: keycloak
    volumes:
      - ./imports/sportship-realm.json:/opt/jboss/keycloak/imports/sportship-realm.json
    ports:
      - 8085:8080
    depends_on:
      - mysql
    restart: 'unless-stopped'
    networks:
      - sportship-network

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: rootnode
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sportship-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8086:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - sportship-network


networks:
  sportship-network:
    driver: bridge
    name: sportship-network

volumes:
  kcdata:
    driver: local
  pgdata:
    driver: local
  pgadmin-data:
    driver: local
